# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_profile_fitbit_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ttam_token',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
