# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_profile_ttam_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genotype_id', models.IntegerField()),
                ('pretty_id', models.CharField(max_length=1000)),
                ('value', models.FloatField()),
            ],
        ),
    ]
