# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_phenotype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phenotype',
            old_name='pretty_id',
            new_name='phenotype_id',
        ),
        migrations.RemoveField(
            model_name='phenotype',
            name='genotype_id',
        ),
        migrations.AddField(
            model_name='phenotype',
            name='profile_id',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
